apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/opensearch
    repoURL: https://github.com/s16837/test-deployment.git #TODO Update me
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

exporters:
    otlp:
        endpoint: "http://opensearch-opensearch-dashboards:4317"
        tls:
            insecure: true

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp]