apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opensearch
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/opensearch
    repoURL: https://github.com/s16837/test-deployment.git #TODO Update me
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


receivers:
  otlp:
    protocols:
      grpc:
      http:


processors:
  batch:
  servicemap:


exporters:
    opensearch:
        endpoint: "http://opensearch-cluster-url:9200"
        insecure_skip_verify: true


service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch, servicemap]
            exporters: [opensearch]